# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13ef3fae13aa3b22d0371627f22614454870c808313044c6b97912bafa1d26545bfc2b0e4bffa3d030b37d11f523cfbe62bf03a3c8e3d5fb8f8de5ca0eee04c2

test:
  secret_key_base: 828a36715f9593fedbd71beb0a958f5362286e0ed55b78f88103bbe6925209f6be9006f5da67d3462762c9dbe15eeb2ade589c7fd3e07600fdf0d04911523a8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
